services:
  stream_engine:
    build:
      context: ../
      dockerfile: docker/stream_engine/Dockerfile
    container_name: stream_engine
    environment:
      - STREAM_DURATION=3
    depends_on:
      - kafka
      - flink-job_manager
    networks:
      - sabd_network


  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    volumes:
      - kafka_volume:/var/lib/kafka/data
    networks:
      - sabd_network

  flink-job_manager:
    build:
      context: ../
      dockerfile: docker/Flink/Dockerfile
    container_name: jobmanager
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    command: standalone-job --job-classname it.sabd.Main
    environment:
      - RUN_ID=${RUN_ID}
      - FLINK_PARALLELISM=${FLINK_PARALLELISM}
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: ${FLINK_PARALLELISM}
        metrics.reporter.influxdb.factory.class: org.apache.flink.metrics.influxdb.InfluxdbReporterFactory
        metrics.reporter.influxdb.host: influxdb
        metrics.reporter.influxdb.port: 8086
        metrics.reporter.influxdb.db: flink_metrics
        metrics.reporter.influxdb.username: results
        metrics.reporter.influxdb.password: ${INFLUX_TOKEN}
        metrics.reporter.influxdb.interval: 10 SECONDS
    networks:
      - sabd_network


  flink-task_manager:
    build:
      context: ../
      dockerfile: docker/Flink/Dockerfile
    container_name: taskmanager
    depends_on:
      - flink-job_manager
    command: taskmanager
    environment:
      - RUN_ID=${RUN_ID}
      - FLINK_PARALLELISM=${FLINK_PARALLELISM}
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        metrics.reporter.influxdb.factory.class: org.apache.flink.metrics.influxdb.InfluxdbReporterFactory
        metrics.reporter.influxdb.host: influxdb
        metrics.reporter.influxdb.port: 8086
        metrics.reporter.influxdb.db: flink_metrics
        metrics.reporter.influxdb.username: results
        metrics.reporter.influxdb.password: ${INFLUX_TOKEN}
        metrics.reporter.influxdb.interval: 10 SECONDS
        parallelism.default: ${FLINK_PARALLELISM}
    networks:
      - sabd_network


  csv_consumer:
    build:
      context: ../
      dockerfile: docker/csv_consumer/Dockerfile
    container_name: csv_consumer
    depends_on:
      - kafka
      - flink-job_manager
    volumes:
      - ../Results:/app/Results
    networks:
      - sabd_network

  influxdb_consumer:
    build:
      context: ../
      dockerfile: docker/influxdb_consumer/Dockerfile
    container_name: influxdb_consumer
    depends_on:
      - kafka
      - flink-job_manager
    environment:
      DOCKER_INFLUXDB_INIT_ORG: results
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
    networks:
      - sabd_network


  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
        DOCKER_INFLUXDB_INIT_MODE: setup
        DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USER}
        DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASS}
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
        DOCKER_INFLUXDB_INIT_ORG: results
        DOCKER_INFLUXDB_INIT_BUCKET: home
    volumes:
        - type: volume
          source: influxdb2-data
          target: /var/lib/influxdb2
        - type: volume
          source: influxdb2-config
          target: /etc/influxdb2
    networks:
      - sabd_network


  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
       - INFLUX_TOKEN=${INFLUX_TOKEN}
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./Grafana/config/datasources:/etc/grafana/provisioning/datasources
      - ./Grafana/config/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - sabd_network


volumes:
  kafka_volume:
  grafana_storage:
  influxdb2-data:
  influxdb2-config:

networks:
  sabd_network:
    driver: bridge
